### ISSUE TITLE
Solutions are not working

### ISSUE THREAD

**Issue by pPanda-beta** [wj32/Judge#1]
The solution [HackerRank/Dijkstra-Shortest Reach 2.cpp](https://github.com/wj32/Judge/blob/master/HackerRank/Dijkstra-%20Shortest%20Reach%202.cpp)
is not working with present test cases.
[Try here first](https://www.hackerrank.com/challenges/dijkstrashortreach)
**Test case 7 is getting TLE.**

**Comment by wj32** [comment]
Thanks, fixed. Looks like it was an issue with cin and cout being very slow compared to scanf and printf.
